spring.application.name=API-Gateway

## spring cloud gatway config
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#Routing logic product
spring.cloud.gateway.routes[0].id=product-api
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/place/**

#Routing logic notification
spring.cloud.gateway.routes[1].id=notifiaction-api
spring.cloud.gateway.routes[1].uri=lb://NOTIFICATION-API
spring.cloud.gateway.routes[1].predicates[0]=Path=/notification/**

server.port=3333